# Generated by Django 3.1.3 on 2020-12-08 11:35

import WebAnalyzer.utils.filename
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiModalModel',
            fields=[
                ('video', models.FileField(null=True, upload_to=WebAnalyzer.utils.filename.default)),
                ('video_url', models.TextField(null=True)),
                ('aggregation_result', models.JSONField()),
                ('token', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('result', django_mysql.models.JSONField(default=dict, null=True)),
            ],
        ),
    ]
