# Generated by Django 3.1.3 on 2020-12-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimodalmodel',
            name='aggregation_result',
            field=models.TextField(),
        ),
    ]
